#!/usr/bin/env python3

from datetime import date
import argparse
import os
import subprocess
import resource

def main():
    now = date.today()
    program = argparse.ArgumentParser(prog="AOC Runner", description="Wrapper to run AOC solutions")
    _ = program.add_argument("-test", action='store_true')
    _ = program.add_argument("year", default=now.year, type=str, nargs="?")
    _ = program.add_argument("day", default=now.day, type=str, nargs="?")

    args = program.parse_args()

    os.chdir(f"./{args.year}/{args.day}")

    command = f"go run . {"-test" if args.test else ""}".split(" ")
    usage_start = resource.getrusage(resource.RUSAGE_CHILDREN)
    command = subprocess.run(command, capture_output=True, text=True)
    usage_end = resource.getrusage(resource.RUSAGE_CHILDREN)
    cpu_time = usage_end.ru_utime - usage_start.ru_utime

    print(command.stdout)
    print(command.stderr)
    print("Time To Run:", cpu_time)

if __name__ == "__main__":
    main()
